@base_url = http://localhost:4000/api

POST {{base_url}}/signup
Content-Type: application/json

{
	"name": "John Doe",
	"email": "john@mail.com",
	"password": "password"
}
###
POST {{base_url}}/signin
Content-Type: application/json

{
	"email": "john@mail.com",
	"password": "password"
}