@base_url = http://localhost:4000/api
@token = Bearer {{login.response.body.access_token}}
@task_id = d2281bd7-c263-4bf8-a41b-0e3e702545e7

# @name signup
POST {{base_url}}/signup
Content-Type: application/json

{
	"name": "John Doe",
	"email": "john@mail.com",
	"password": "password"
}
###

# @name login
POST {{base_url}}/signin
Content-Type: application/json

{
	"email": "john@mail.com",
	"password": "password"
}
###

# @name create_task
POST {{base_url}}/tasks
Content-Type: application/json
Authorization: {{token}}

{
	"title": "Task 1"
}
###

GET {{base_url}}/tasks?page=1
Authorization: {{token}}

###

# @name complete_task
PATCH {{base_url}}/tasks/{{task_id}}/complete
Authorization: {{token}}

###
# @name update_task
PATCH {{base_url}}/tasks/{{task_id}}
Content-Type: application/json
Authorization: {{token}}

{
	"title": "Task 1 Updated"
}