@base_url = http://localhost:4000/api
@token = Bearer {{login.response.body.access_token}}
@task_id = {{create_task.response.body.id}}

# @name signup
POST {{base_url}}/signup
Content-Type: application/json

{
	"name": "John Doe",
	"email": "john@mail.com",
	"password": "password"
}
###

# @name login
POST {{base_url}}/signin
Content-Type: application/json

{
	"email": "john@mail.com",
	"password": "password"
}
###

# @name create_task
POST {{base_url}}/tasks
Content-Type: application/json
Authorization: {{token}}

{
	"title": "Task 1"
}
###

GET {{base_url}}/tasks?page=1
Authorization: {{token}}

###
PATCH {{base_url}}/tasks/{{task_id}}/complete
Authorization: {{token}}